/* Generated by scripts/write */
/* Don't edit this file directly */
export const all = ['ru_RU','nl','pt_PT','pl','en_US','es_MX','fr_FR','fi','nn','sv_SE','es_ES','id_ID','it_IT','nb','pt_BR','ar','ja_JP','tr_TR','fa','cs','de_DE']
export const complete = ['ru_RU','pt_PT','pl','en_US','es_MX','fr_FR','fi','nn','sv_SE','es_ES','id_ID','nb','pt_BR','ar','ja_JP','tr_TR','fa','cs','de_DE']