const fs = require('fs')
const yaml = require('js-yaml')
const parse = require('./parse')

const dir = './dist'
const dirs = ['/json', '/yaml', '/md']

let versionsLen = 0
let versions = []

/**
 *  Make sure dirs exist
 */
if (!fs.existsSync(dir)) fs.mkdirSync(dir)
dirs.forEach(d => {
  if (!fs.existsSync(`${dir}${d}`)) {
    fs.mkdirSync(`${dir}${d}`)
  }
})


/**
 *  Write to versions.js
 */
const writeToVersionsFile = vers => {
  const dcr1 = "/* Generated by scripts/write */"
  const dcr2 = "/* Don't edit this file directly */"
  const all = `['${vers.map(v => v.id).join("','")}']`
  const com = `['${vers.filter(v => v.complete).map(v => v.id).join("','")}']`
  const val = `${dcr1}\n${dcr2}\nexport const all = ${all}\nexport const complete = ${com}`

  fs.writeFile('./versions.js', val, { flag: 'w' }, err => {
    if (err) return console.log(err)
    console.log('Wrote versions state to ./versions.js')
  })
}


/**
 *  Write to files
 */
const writeFile = data => {
  const dataJson = JSON.stringify(data)
  const dataYaml = yaml.dump(data)

  fs.writeFile(`${dir}/json/${data.meta.id}.json`, dataJson, { flag: 'w' }, err => {
    if (err) return console.log(err)
    console.log(`Wrote to ${dir}/json/${data.meta.id}.json`)
  })

  fs.writeFile(`${dir}/yaml/${data.meta.id}.yml`, dataYaml, { flag: 'w' }, err => {
    if (err) return console.log(err)
    console.log(`Wrote to ${dir}/yaml/${data.meta.id}.yml`)
  })

  // Update list of versions and whether they're complete
  versions.push({
    id: data.meta.id,
    complete: JSON.parse(data.meta.complete)
  })

  // Write to versions.js
  if (versions.length === versionsLen) {
    writeToVersionsFile(versions)
  }
}


/**
 *  Parse source md files
 *  and write to dist
 */

fs.readdir('./versions', (err, paths) => {
  if (err) return console.log(err)

  paths.forEach(p => {
    const id = p.substring(0, p.indexOf('.'))
    parse(id, writeFile)

    versionsLen += 1

    fs.copyFile(`./versions/${p}`, `./dist/md/${p}`, 0, (err, res) => {
      if (err) return console.log('bolle', err)
      console.log(`Wrote to ./dist/md/${p}`)
    })
  })
})